
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata: 
      labels: 
        app: jenkins
    spec: 
      containers: 
        - image: docker.io/library/jenkins:latest
          name: jenkins
          ports: 
            - containerPort: 8080
          volumeMounts: 
          - mountPath: /var/jenkins_home
            name: jenkins-home
      volumes: 
        - emptyDir: {}
          name: jenkins-home
